
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 150
StringLiterals:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/GuardClause:
  Enabled: false
